CREATE VIEW V_SALES_REPORT(Sales_ID,Sales_Date,Product_ID,Product_Name,Quantity_Sold,Product_Unit_Price,Sales_Price_Per_Unit,Profit_Amount)
AS
SELECT SL.SALES_ID,SL.SALES_DATE,SL.PRODUCT_ID,ST.PRODUCT_NAME,SL.QUANTITY_SOLD,ST.PRODUCT_UNIT_PRICE,SL.SALES_PRICE_PER_UNIT,(SL.SALES_PRICE_PER_UNIT-ST.PRODUCT_UNIT_PRICE) pa FROM TBL_STOCK ST,TBL_SALES SL WHERE SL.PRODUCT_ID=ST.PRODUCT_ID 
ORDER BY pa DESC,SL.Sales_id ASC;
