CREATE TABLE TBL_STOCK(
Product_ID VARCHAR2(6) CONSTRAINT STK_PID_PK PRIMARY KEY,
Product_Name VARCHAR2(20) CONSTRAINT STK_PNAME_UQ UNIQUE,
Quantity_On_Hand NUMBER CONSTRAINT STK_QOH CHECK (Quantity_On_Hand>=0),
Product_Unit_Price NUMBER CONSTRAINT STK_PUP CHECK (Product_Unit_Price>=0),
Reorder_Level NUMBER CONSTRAINT STK_RL CHECK (Reorder_Level>=0));

CREATE TABLE TBL_SALES(
Sales_ID VARCHAR2(6) CONSTRAINT SAL_SID_PK PRIMARY KEY,
Sales_Date DATE,
Product_ID VARCHAR2(6),
Quantity_Sold NUMBER CONSTRAINT SAL_QS CHECK (Quantity_Sold>=0),
Sales_Price_Per_Unit NUMBER CONSTRAINT SAL_SPU CHECK (Sales_Price_Per_Unit>=0),
CONSTRAINT SAL_FK FOREIGN KEY (Product_ID) REFERENCES TBL_STOCK(Product_ID));


